/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_advantech_advnfc_AdvNFC */

#ifndef _Included_com_advantech_advnfc_AdvNFC
#define _Included_com_advantech_advnfc_AdvNFC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_advantech_advnfc_AdvNFC
 * Method:    doInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_advantech_advnfc_AdvNFC_doInit
  (JNIEnv *, jobject);

/*
 * Class:     com_advantech_advnfc_AdvNFC
 * Method:    scan
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_advantech_advnfc_AdvNFC_scan
  (JNIEnv *, jobject);

/*
 * Class:     com_advantech_advnfc_AdvNFC
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_advantech_advnfc_AdvNFC_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
