/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_advantech_advnfc_AdvNFC */

#ifndef _Included_com_advantech_advnfc_AdvNFC
#define _Included_com_advantech_advnfc_AdvNFC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_advantech_advnfc_AdvNFC
 * Method:    loadKey
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_advantech_advnfc_AdvNFC_loadKey
  (JNIEnv *, jobject);

/*
 * Class:     com_advantech_advnfc_AdvNFC
 * Method:    readCard
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_advantech_advnfc_AdvNFC_readCard
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
